### Stage 1: build ###

FROM node:12-alpine as builder

# Set working directory.
WORKDIR /app

# Copy dependencies.
COPY $PWD/frontend/package.json $PWD/frontend/package-lock.json /app/frontend/

# Install app dependencies.
RUN npm install --prefix frontend

#Copy app files.
COPY $PWD/frontend/ /app/frontend

# Build app
RUN npm run build --prefix frontend -- --output-path=/app/frontend/dist/out



### Stage 2: delivery ###

FROM nginx:latest

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy output directory from builder to nginx image.
COPY --from=builder /app/frontend/dist/out /usr/share/nginx/html

# Copy nginx configuration file.
COPY default.conf /etc/nginx/conf.d/default.conf